### ISSUE TITLE
Windows 7 compatibility

### ISSUE THREAD

**Issue by e-tcy** [fleasion/Fleasion#1]
Yes, Roblox still runs on Windows 7.
And the latest Python version on there is 3.8.
As said [here](https://discord.com/channels/1163716337210773518/1180755591392677968/1270618740786073661), this is fixable by rewriting `match` cases to `if` chains.

anyways it would be funny (i play roblox on my laptop from 2010)

**Comment by e-tcy** [comment]
probably could do it manually im just lazy

**Comment by WatermelonEnjoyer0** [comment]
js update to windows 10 bruh 😭 🙏

**Comment by e-tcy** [comment]
nah
